[General]
Aur_Tool_Name=paru
Backend=alpm
Cache_Cleaner_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2N\0\0\x1@\0\0\x5\x31\0\0\x3\x10\0\0\x2N\0\0\x1@\0\0\x5\x31\0\0\x3\x10\0\0\0\0\0\0\0\0\a\x80\0\0\x2N\0\0\x1@\0\0\x5\x31\0\0\x3\x10)
Current_Tab_Index=3
Distro_RSS_Url=https://archlinux.org/feeds/news/
Instant_Search=true
Keep_Num_Installed=0
Keep_Num_Uninstalled=0
LastCheckUpdatesTime=@DateTime(\0\0\0\x10\0\0\0\0\0\0%\x8b\x37\x2Ym\xc9\0)
OptionalDeps_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0$\0\0\x2/\0\0\x1\xb5\0\0\0\0\0\0\0$\0\0\x2/\0\0\x1\xb5\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0$\0\0\x2/\0\0\x1\xb5)
OutputDialog_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2{\0\0\x1\x14\0\0\x5\x4\0\0\x3#\0\0\x2{\0\0\x1\x30\0\0\x5\x4\0\0\x3#\0\0\0\0\0\0\0\0\a\x80\0\0\x2{\0\0\x1\x30\0\0\x5\x4\0\0\x3#)
PackageList_Ordered_Col=1
PackageList_Sort_Order=0
Package_Download_Size_Column_Width=803
Package_Icon_Column_Width=49
Package_Name_Column_Width=400
Package_Repository_Column_Width=150
Package_Version_Column_Width=260
Panel_Organizing=30
Repo_Editor_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc0\0\0\x1!\0\0\aC\0\0\x2\xca\0\0\x3\xc0\0\0\x1!\0\0\aC\0\0\x2\xca\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc0\0\0\x1!\0\0\aC\0\0\x2\xca)
Show_Groups_Panel=false
Splitter_Horizontal_State=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\0\xc8\0\0\0\xeb\x1\xff\xff\xff\xff\x1\0\0\0\x2\0)
Transaction_Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\x1\0\0\0\x1c\0\0\x1\xea\0\0\x1\x85\0\0\0\x1\0\0\0\x1c\0\0\x1\xea\0\0\x1\x85\0\0\0\0\0\0\0\0\a\x80\0\0\0\x1\0\0\0\x1c\0\0\x1\xea\0\0\x1\x85)
Use_Default_App_Icon=true
Window_Size=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc0\0\0\0\x1c\0\0\a\x7f\0\0\x4\x37\0\0\x3\xc0\0\0\0\x1c\0\0\a\x7f\0\0\x4\x37\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc0\0\0\0\x1c\0\0\a\x7f\0\0\x4\x37)
