Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "close,maximize,minimize:icon"
Net/ThemeName "Breeze-Dark"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gtk/CursorThemeSize 24
Gtk/CursorThemeName "Dracula-cursors"
Net/SoundThemeName "Harmony2"
Net/IconThemeName "Flat-Remix-Blue-Light-darkPanel"
Gtk/FontName "Noto Sans,  10"

